Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Commands\\FlushSessions",
            "name": "FlushSessions",
            "summary": "",
            "url": "classes/App-Console-Commands-FlushSessions.html"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FlushSessions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020command\u0020instance.",
            "url": "classes/App-Console-Commands-FlushSessions.html#method___construct"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FlushSessions\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-FlushSessions.html#method_handle"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FlushSessions\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/App-Console-Commands-FlushSessions.html#property_signature"
        },                {
            "fqsen": "\\App\\Console\\Commands\\FlushSessions\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/App-Console-Commands-FlushSessions.html#property_description"
        },                {
            "fqsen": "\\App\\Http\\Contracts\\AuthentificationInterface",
            "name": "AuthentificationInterface",
            "summary": "Interface\u0020for\u0020user\u0020authentication\u0020and\u0020session\u0020management.",
            "url": "classes/App-Http-Contracts-AuthentificationInterface.html"
        },                {
            "fqsen": "\\App\\Http\\Contracts\\AuthentificationInterface\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Authenticate\u0020and\u0020log\u0020a\u0020user\u0020into\u0020the\u0020system.",
            "url": "classes/App-Http-Contracts-AuthentificationInterface.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Contracts\\AuthentificationInterface\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Terminate\u0020an\u0020active\u0020user\u0020session\u0020and\u0020log\u0020the\u0020user\u0020out.",
            "url": "classes/App-Http-Contracts-AuthentificationInterface.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Contracts\\FileHandlerInterface",
            "name": "FileHandlerInterface",
            "summary": "Interface\u0020for\u0020handling\u0020file\u0020operations.",
            "url": "classes/App-Http-Contracts-FileHandlerInterface.html"
        },                {
            "fqsen": "\\App\\Http\\Contracts\\FileHandlerInterface\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Upload\u0020a\u0020file\u0020to\u0020the\u0020server.",
            "url": "classes/App-Http-Contracts-FileHandlerInterface.html#method_upload"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APICSVImportController",
            "name": "APICSVImportController",
            "summary": "Controller\u0020for\u0020handling\u0020CSV\u0020imports\u0020via\u0020API.",
            "url": "classes/App-Http-Controllers-API-APICSVImportController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APICSVImportController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020APICSVImportController.",
            "url": "classes/App-Http-Controllers-API-APICSVImportController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APICSVImportController\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Upload\u0020and\u0020import\u0020CSV\u0020file.",
            "url": "classes/App-Http-Controllers-API-APICSVImportController.html#method_upload"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APICSVImportController\u003A\u003A\u0024responseService",
            "name": "responseService",
            "summary": "Handles\u0020standardized\u0020JSON\u0020responses.",
            "url": "classes/App-Http-Controllers-API-APICSVImportController.html#property_responseService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APICSVImportController\u003A\u003A\u0024contactCSVHandlerService",
            "name": "contactCSVHandlerService",
            "summary": "Handles\u0020CSV\u0020file\u0020processing\u0020and\u0020import\u0020logic.",
            "url": "classes/App-Http-Controllers-API-APICSVImportController.html#property_contactCSVHandlerService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\ApiLoginController",
            "name": "ApiLoginController",
            "summary": "Controller\u0020for\u0020handling\u0020API\u0020login\u0020and\u0020logout\u0020functionalities.",
            "url": "classes/App-Http-Controllers-API-ApiLoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\ApiLoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020ApiLoginController\u0020with\u0020required\u0020services.",
            "url": "classes/App-Http-Controllers-API-ApiLoginController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\ApiLoginController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Log\u0020out\u0020a\u0020user\u0020from\u0020the\u0020API.",
            "url": "classes/App-Http-Controllers-API-ApiLoginController.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\ApiLoginController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Log\u0020in\u0020a\u0020user\u0020to\u0020the\u0020API.",
            "url": "classes/App-Http-Controllers-API-ApiLoginController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\ApiLoginController\u003A\u003A\u0024responseService",
            "name": "responseService",
            "summary": "Service\u0020for\u0020managing\u0020and\u0020standardizing\u0020JSON\u0020responses.",
            "url": "classes/App-Http-Controllers-API-ApiLoginController.html#property_responseService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\ApiLoginController\u003A\u003A\u0024sanctumAuthenticationService",
            "name": "sanctumAuthenticationService",
            "summary": "Service\u0020for\u0020handling\u0020Sanctum\u002Dbased\u0020authentication\u0020processes.",
            "url": "classes/App-Http-Controllers-API-ApiLoginController.html#property_sanctumAuthenticationService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APIUserController",
            "name": "APIUserController",
            "summary": "Controller\u0020for\u0020retrieving\u0020information\u0020about\u0020the\u0020authenticated\u0020API\u0020user.",
            "url": "classes/App-Http-Controllers-API-APIUserController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APIUserController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020an\u0020instance\u0020of\u0020APIUserController\u0020with\u0020required\u0020services.",
            "url": "classes/App-Http-Controllers-API-APIUserController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APIUserController\u003A\u003AgetLoggedInUser\u0028\u0029",
            "name": "getLoggedInUser",
            "summary": "Retrieve\u0020the\u0020authenticated\u0020user\u0020based\u0020on\u0020the\u0020active\u0020token.",
            "url": "classes/App-Http-Controllers-API-APIUserController.html#method_getLoggedInUser"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APIUserController\u003A\u003A\u0024responseService",
            "name": "responseService",
            "summary": "Service\u0020for\u0020formatting\u0020and\u0020managing\u0020JSON\u0020responses.",
            "url": "classes/App-Http-Controllers-API-APIUserController.html#property_responseService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\APIUserController\u003A\u003A\u0024sanctumAuthenticationService",
            "name": "sanctumAuthenticationService",
            "summary": "Service\u0020for\u0020managing\u0020user\u0020authentication\u0020and\u0020retrieving\u0020user\u0020data\u0020based\u0020on\u0020Sanctum\u0020tokens.",
            "url": "classes/App-Http-Controllers-API-APIUserController.html#property_sanctumAuthenticationService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "Abstract\u0020base\u0020controller\u0020class\u0020for\u0020the\u0020application.",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVImportController",
            "name": "CSVImportController",
            "summary": "Controller\u0020for\u0020handling\u0020CSV\u0020import\u0020functionalities.",
            "url": "classes/App-Http-Controllers-CSVImportController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVImportController\u003A\u003AloadForm\u0028\u0029",
            "name": "loadForm",
            "summary": "Load\u0020the\u0020CSV\u0020import\u0020form\u0020view.",
            "url": "classes/App-Http-Controllers-CSVImportController.html#method_loadForm"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVImportController\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Upload\u0020a\u0020CSV\u0020file\u0020to\u0020the\u0020external\u0020API.",
            "url": "classes/App-Http-Controllers-CSVImportController.html#method_upload"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController",
            "name": "LoginController",
            "summary": "Controller\u0020for\u0020managing\u0020user\u0020login\u0020and\u0020logout\u0020functionalities.",
            "url": "classes/App-Http-Controllers-LoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020LoginController\u0020with\u0020required\u0020services.",
            "url": "classes/App-Http-Controllers-LoginController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Log\u0020out\u0020the\u0020user\u0020from\u0020the\u0020frontend.",
            "url": "classes/App-Http-Controllers-LoginController.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Log\u0020in\u0020the\u0020user\u0020via\u0020an\u0020API\u0020call.",
            "url": "classes/App-Http-Controllers-LoginController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\LoginController\u003A\u003A\u0024sessionAuthenticationService",
            "name": "sessionAuthenticationService",
            "summary": "Service\u0020for\u0020handling\u0020session\u002Dbased\u0020authentication\u0020processes.",
            "url": "classes/App-Http-Controllers-LoginController.html#property_sessionAuthenticationService"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\CheckSanctumToken",
            "name": "CheckSanctumToken",
            "summary": "Middleware\u0020to\u0020check\u0020for\u0020a\u0020Sanctum\u0020authentication\u0020token\u0020in\u0020the\u0020session.",
            "url": "classes/App-Http-Middleware-CheckSanctumToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\CheckSanctumToken\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request\u0020and\u0020check\u0020for\u0020a\u0020login\u0020token\u0020in\u0020the\u0020session.",
            "url": "classes/App-Http-Middleware-CheckSanctumToken.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Services\\ContactCSVHandlerService",
            "name": "ContactCSVHandlerService",
            "summary": "Service\u0020for\u0020handling\u0020CSV\u0020file\u0020uploads\u0020and\u0020processing\u0020contact\u0020data.",
            "url": "classes/App-Http-Services-ContactCSVHandlerService.html"
        },                {
            "fqsen": "\\App\\Http\\Services\\ContactCSVHandlerService\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Uploads\u0020and\u0020processes\u0020a\u0020CSV\u0020file\u0020from\u0020the\u0020incoming\u0020request.",
            "url": "classes/App-Http-Services-ContactCSVHandlerService.html#method_upload"
        },                {
            "fqsen": "\\App\\Http\\Services\\ResponseService",
            "name": "ResponseService",
            "summary": "Service\u0020for\u0020managing\u0020standardized\u0020JSON\u0020responses.",
            "url": "classes/App-Http-Services-ResponseService.html"
        },                {
            "fqsen": "\\App\\Http\\Services\\ResponseService\u003A\u003AsendResponse\u0028\u0029",
            "name": "sendResponse",
            "summary": "Sends\u0020a\u0020successful\u0020JSON\u0020response.",
            "url": "classes/App-Http-Services-ResponseService.html#method_sendResponse"
        },                {
            "fqsen": "\\App\\Http\\Services\\ResponseService\u003A\u003AsendError\u0028\u0029",
            "name": "sendError",
            "summary": "Sends\u0020an\u0020error\u0020JSON\u0020response.",
            "url": "classes/App-Http-Services-ResponseService.html#method_sendError"
        },                {
            "fqsen": "\\App\\Http\\Services\\ResponseService\u003A\u003AsendStandardResponse\u0028\u0029",
            "name": "sendStandardResponse",
            "summary": "Constructs\u0020and\u0020sends\u0020a\u0020standardized\u0020JSON\u0020response.",
            "url": "classes/App-Http-Services-ResponseService.html#method_sendStandardResponse"
        },                {
            "fqsen": "\\App\\Http\\Services\\SanctumAuthenticationService",
            "name": "SanctumAuthenticationService",
            "summary": "Service\u0020for\u0020handling\u0020authentication\u0020using\u0020Laravel\u0020Sanctum.",
            "url": "classes/App-Http-Services-SanctumAuthenticationService.html"
        },                {
            "fqsen": "\\App\\Http\\Services\\SanctumAuthenticationService\u003A\u003AgetPersonalToken\u0028\u0029",
            "name": "getPersonalToken",
            "summary": "Retrieve\u0020the\u0020personal\u0020access\u0020token\u0020from\u0020the\u0020request.",
            "url": "classes/App-Http-Services-SanctumAuthenticationService.html#method_getPersonalToken"
        },                {
            "fqsen": "\\App\\Http\\Services\\SanctumAuthenticationService\u003A\u003AgetLoggedInUser\u0028\u0029",
            "name": "getLoggedInUser",
            "summary": "Retrieve\u0020the\u0020user\u0020associated\u0020with\u0020the\u0020active\u0020access\u0020token.",
            "url": "classes/App-Http-Services-SanctumAuthenticationService.html#method_getLoggedInUser"
        },                {
            "fqsen": "\\App\\Http\\Services\\SanctumAuthenticationService\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Log\u0020in\u0020a\u0020user\u0020and\u0020generate\u0020a\u0020Sanctum\u0020token.",
            "url": "classes/App-Http-Services-SanctumAuthenticationService.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Services\\SanctumAuthenticationService\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Log\u0020out\u0020a\u0020user\u0020by\u0020invalidating\u0020the\u0020Sanctum\u0020token.",
            "url": "classes/App-Http-Services-SanctumAuthenticationService.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Services\\SessionAuthenticationService",
            "name": "SessionAuthenticationService",
            "summary": "Service\u0020for\u0020handling\u0020session\u002Dbased\u0020authentication.",
            "url": "classes/App-Http-Services-SessionAuthenticationService.html"
        },                {
            "fqsen": "\\App\\Http\\Services\\SessionAuthenticationService\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Log\u0020in\u0020a\u0020user\u0020by\u0020storing\u0020the\u0020authentication\u0020token\u0020in\u0020the\u0020session.",
            "url": "classes/App-Http-Services-SessionAuthenticationService.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Services\\SessionAuthenticationService\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Log\u0020out\u0020a\u0020user\u0020by\u0020clearing\u0020the\u0020session\u0020data\u0020and\u0020regenerating\u0020the\u0020CSRF\u0020token.",
            "url": "classes/App-Http-Services-SessionAuthenticationService.html#method_logout"
        },                {
            "fqsen": "\\App\\Models\\Contact",
            "name": "Contact",
            "summary": "",
            "url": "classes/App-Models-Contact.html"
        },                {
            "fqsen": "\\App\\Models\\Contact\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-Contact.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "Get\u0020the\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Aunverified\u0028\u0029",
            "name": "unverified",
            "summary": "Indicate\u0020that\u0020the\u0020model\u0027s\u0020email\u0020address\u0020should\u0020be\u0020unverified.",
            "url": "classes/Database-Factories-UserFactory.html#method_unverified"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003A\u0024password",
            "name": "password",
            "summary": "The\u0020current\u0020password\u0020being\u0020used\u0020by\u0020the\u0020factory.",
            "url": "classes/Database-Factories-UserFactory.html#property_password"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UserSeeder",
            "name": "UserSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UserSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UserSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-UserSeeder.html#method_run"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Feature-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest\u003A\u003Atest_the_application_returns_a_successful_response\u0028\u0029",
            "name": "test_the_application_returns_a_successful_response",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Feature-ExampleTest.html#method_test_the_application_returns_a_successful_response"
        },                {
            "fqsen": "\\Tests\\TestCase",
            "name": "TestCase",
            "summary": "",
            "url": "classes/Tests-TestCase.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Unit-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest\u003A\u003Atest_that_true_is_true\u0028\u0029",
            "name": "test_that_true_is_true",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Unit-ExampleTest.html#method_test_that_true_is_true"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/app-console-commands.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "namespaces/app-http-contracts.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API",
            "name": "API",
            "summary": "",
            "url": "namespaces/app-http-controllers-api.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Http\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-http-services.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Tests\\Feature",
            "name": "Feature",
            "summary": "",
            "url": "namespaces/tests-feature.html"
        },                {
            "fqsen": "\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/tests.html"
        },                {
            "fqsen": "\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/tests-unit.html"
        }            ]
);
